language: nix
sudo: required

before_script:
  # cachix
  - sudo mount -o remount,exec,size=4G,mode=755 /run/user || true

script:
- nix-env -iA cachix -f https://cachix.org/api/v1/install --extra-substituters https://cachix.cachix.org --trusted-public-keys 'cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM='
- cachix use gi-gtk-declarative
- |
  # build and run tests
  nix-build -j2 -A gi-gtk-declarative --arg doCheck true
  # building `examples` will also build the libraries
  if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
     cachix push gi-gtk-declarative --watch-store&
     nix-build -j2 -A examples | cachix push gi-gtk-declarative
  else
     nix-build -j2 -A examples
  fi
env:
  global:
    secure: GOD2qKeWoVZYesTZhJeukdoAbYmyG5wm/Nfp1W8TKL8oHoezqNkK12qOCpMlQB9EfjgIoQabSp0/3UENXgKIvA0H5uW5M+7gEVM/gnE3QZoFGYUMlhpQ9sr5JFg8ORbxop1d5+5Q4HvvtDzgxbwjD4m+gd6RKCFf92EqSVEIKQKDldUdz4tJIKDjWDLl9ewelMLV6Q+rDyI+wRa8OqprKIhkiNBuothIIeBiQIfN2vNN+s+Gi8Wi8lC8VCG7p6gW3cQUk7E0q19+2tl6BaRlN5m2qMfjMqlZ6NljCDN6UNTlGxFG7VEjOkLLsz3Zdm8nE78bVE2MDM5gIi9fOSECKzk8gpa8iWA3rA2/J26SBZ1EsrIi1uppxhac6+u9u2iuF34uEpIUv/RCX0d1S2Ogp5nQyW0DUv0hIE3lc6SRmtyVkeu+mYKHF58+QKt2hHwmHDgYEQxQcmamW1z6GENe5a+MHJ45pkb1gNuZcPVdSwXuEmIaarNrc8iOR23AZvdpZXau/gXwQg3CL4FmCtV/MTr+QuLr/PUiiSHgMJHTWKwysHKbsG4u8aSN4gl5nWmYIEKv0rf0mE3UwVPEGBjJz7OpiogFGIiTCR3+sdE1SOImlb+TmHmTnLp/nC61Cy++ZBWxv6QC8PguEf0LTHj3xd6M6ridilud1UbGxKDt7i0=
