site_name: gi-gtk-declarative
site_description: 'Documentation for the gi-gtk-declarative package.'
site_author: 'Oskar Wickström'
copyright: 'Copyright © 2018 Oskar Wickström'
docs_dir: src
nav:
    - installation.md
    - 'Widgets':
        - widgets/the-widget-type.md
        - widgets/single-widgets.md
        - widgets/bins.md
        - widgets/containers.md
        - widgets/custom-widgets.md
    - 'Attributes':
        - attributes/properties.md
        - attributes/events.md
        - attributes/css.md
    - app-simple.md
    - contributing.md
theme:
  name: 'material'
  font:
    text: 'Source Sans Pro'
    code: 'Source Code Pro'
extra_css:
    - css/theme.css
markdown_extensions:
  - admonition
  - def_list
  - codehilite
